### ISSUE TITLE
칭찬하기 페이지에서 본인, 관리자는 선택할 수 없다.

### ISSUE THREAD

**Issue by Godeng** [wonder13662/barogo-passport#20]
## 목적
유저는 칭찬하기 페이지에 들어갔을 때 칭찬할 사람을 검색할 때 본인, 관리자를 선택할 수 없다.
여권의 목적은 타인에 대한 존중과 감사의 문화를 만드는 것이다. 따라서 본인에게 칭찬, 스티커를 줄 수 없다.
관리자는 별도의 유저용 계정을 가지고 있다. 따라서 관리자를 칭찬하고 싶다면 관리자의 유저용 계정에게 칭찬을 줄 수 있다.

## user story
- 유저 계정으로 칭찬하기 페이지에 들어간다.
- 칭찬하기 페이지에서 칭찬할 사람 인풋창을 클릭한다.
- 본인, 관리자는 검색할 수 없고, 드롭다운을 열어봐도 보이지 않는다.

**Comment by wonder13662** [comment]
구현된 기능입니다. 이슈를 닫을께요!
