### ISSUE TITLE
칭찬하기를 완료하면 '내가 쓴 칭찬' 페이지로 이동한다.

### ISSUE THREAD

**Issue by Godeng** [wonder13662/barogo-passport#21]
##목적
칭찬하기를 통해 칭찬의 등록을 성공하면, 칭찬이 등록되었다는 점을 페이지에서 알려주어야 한다.

## User story
- 칭찬하기 페이지에서 칭찬 내용을 입력 후 칭찬을 완료, 팝업을 닫는다.
- 팝업을 닫음과 동시에 '내가 쓴 칭찬' 페이지로 이동한다.

**Comment by wonder13662** [comment]
구현 완료!
