### ISSUE TITLE
공통 알림 정의 : 5초 후에 사라지는 alert

### ISSUE THREAD

**Issue by Godeng** [wonder13662/barogo-passport#22]
##목적
공통 알림을 만든다.
첫 알림은 5초 후에 사라지는 알림.
유저의 행동에 대해서 성공 / 실패를 알려주기 위한 용도로 사용한다.

## User story
- 가입되지 않은 유저 아이디로 로그인을 시도한다. : '아이디가 없습니다. '처음 오셨나요?' 를 통해 비밀번호를 설정해주세요.'
- 틀린 비밀번호로 로그인을 시도한다. : '비밀번호가 틀립니다.'
- '칭찬하기' 팝업에서 '저장'을 눌렀고, 칭찬이 저장되었다. : (현재 뭐였죠?)
- '칭찬하기' 팝업에서 '저장'을 눌렀으나, 저장에 실패했다. : '저장하지 못했어요. 다시 시도해주세요.'
- 관리자가 유저 목록의 저장을 눌렀고, 유저 목록이 저장되었다. : '직원 목록을 저장했어요.'
- 관리자가 유저 목록의 저장을 눌렀고, 유저 목록 저장에 실패했다. : '직원 목록을 저장하지 못했어요. 다시 시도해주세요.'

**Comment by wonder13662** [comment]
@Godeng 
현재 칭찬이 저장되었을 때는 '칭찬이 성공적으로 작성되었어요!' 라고 노출됩니다. 지금 관리되고 있는 메시지는 아래와 같습니다. 어조나 문장을 제안주시면 반영하도록 할께요. 위에 User story에 있는 내용을 먼저 반영하면 될까요?
```
const MESSAGE = {
  USER: {
    UPLOAD: {
      SUCCESS: '직원 정보 업로드가 완료되었어요!.',
      FAILED: '직원 정보 업로드가 실패했어요.',
    },
  },
  PRAISE: {
    CREATE: {
      SUCCESS: '칭찬이 성공적으로 작성되었어요!',
      FAILED: '칭찬을 쓰는데 실패했어요.',
      FAILED_SERVER_ERROR: '서비스에 문제가 있어서 칭찬을 쓰지 못했어요.',
    },
    UPDATE: {
      SUCCESS: '칭찬이 성공적으로 수정되었어요!',
      FAILED: '칭찬을 수정하다 실패했어요.',
      FAILED_SERVER_ERROR: '서비스에 문제가 있어서 칭찬을 수정하지 못했어요.',
    },
  },
}

```
