### ISSUE TITLE
App-bar UI 피그마 시안과 동일하게 변경

### ISSUE THREAD

**Issue by juhyun94** [wonder13662/barogo-passport#47]
- [x] **OOO님 안녕하세요** 버튼이 아닌 텍스트로 변경
- [x] **페이지 버튼들 스타일 변경**
- [x] **로그아웃 버튼 컬러 변경**
- [x] **App-bar 아랫부분에 border 추가**
- [x] **v-toolbar__content 영역 좌,우 패딩 24px로 변경(가능할지..?)** 

https://www.figma.com/file/SaMU3tZwdX0eS4NwgIzeQO/%EC%82%AC%EC%9D%B4%EB%93%9C%ED%94%8C%EC%A0%9D?node-id=3055%3A4160
![image](https://user-images.githubusercontent.com/73247309/97443963-f86e3080-196e-11eb-9af2-7be48d99d3cc.png)

**Comment by wonder13662** [comment]
@juhyun94 
페이지버튼들의 위치를 왼쪽으로 두는 것이 좋을 것 같아 제안드립니다. 

## 문제
![Screen Shot 2020-11-02 at 8 47 49 AM](https://user-images.githubusercontent.com/15767104/97818866-68bae000-1ce8-11eb-98b4-e7a4e20eb9c7.png)
- 페이지버튼 탭을 오른쪽에 두는 경우, 현재 Appbar 내에서 정렬의 문제가 있다.(선택된 페이지와 선택된 underline의 위치가 맞지 않는 이슈) 이 문제의 원인은 Veutify 내부의 문제이므로 외부에서 해결하는 것은 효율적이지 않다고 판단

## 대안
![Screen Shot 2020-11-02 at 8 48 11 AM](https://user-images.githubusercontent.com/15767104/97818869-6b1d3a00-1ce8-11eb-8919-f51fe5984b86.png)
- 페이지버튼 탭을 왼쪽(기본값)으로 두면, 정렬 문제 해결. 그리고 메뉴와 프로필 액션이 나뉘어 더 정돈되 보이는 효과가 있다.

그럼 확인부탁드릴께요!

**Comment by wonder13662** [comment]
@juhyun94 AppBar의 1px 보더를 넣는 것을 강제로 넣으려고 진행하다가, Vuetify에서 제공하는 기능으로 해결하는 것이 어떨까 해서 제안드립니다.
## 작업이전
![Screen Shot 2020-11-02 at 8 48 11 AM](https://user-images.githubusercontent.com/15767104/97819169-3c07c800-1cea-11eb-97ad-7cb722b7213d.png)
## 작업이후
![Screen Shot 2020-11-02 at 9 01 16 AM](https://user-images.githubusercontent.com/15767104/97819170-3f02b880-1cea-11eb-89e2-0b8b145e32db.png)

Vuetify elevation은 그림자를 만드는 기능인데요, 말씀하신 것과 정확하게 일치하지는 않습니다. 하지만 경계를 구분하는 역할은 할 수 있어서 이번 업데이트 작업에는 이것으로 선택하는 것이 어떨까합니다. 실제로 border를 적용할 엘리먼트를 찾는 작업이 시간이 걸리고 이것을 다음에 작업할 분이 관리해야하는 일이 적지 않을 것 같아 이런 제안드리게 되었습니다. 그럼 의견 부탁드립니다.

**Comment by wonder13662** [comment]
@juhyun94 작업을 완료하였습니다. 의견을 드린 부분에 대해 조율을 하고 이 이슈를 완료하면 좋을 것 같습니다.

**Comment by wonder13662** [comment]
Appbar의 Border의 elavation은 로그인화면에서는 제거

**Comment by wonder13662** [comment]
로고 작아진 것 확인
