### ISSUE TITLE
사용자 관리 페이지 버튼 및 업로드필드 개선

### ISSUE THREAD

**Issue by juhyun94** [wonder13662/barogo-passport#51]
0. 타이틀 제거
1. 목록 다운로드는 왼쪽으로 이동
2. 목록 파일 업로드는 오른쪽 왼편 첫번째
3. 목록 파일 서버 업로드는 오른쪽 왼편 두번째

 플로우 상 파일 올리고 업로드 버튼 클릭 -> 좌에서 우로 이어지는게 자연스러움. 버튼 위치 개선 필요

**Comment by wonder13662** [comment]
@juhyun94 가안으로 잡아본 레이아웃은 아래와 같습니다. 확인부탁드려요.
![Screen Shot 2020-11-02 at 9 52 05 AM](https://user-images.githubusercontent.com/15767104/97820338-17631e80-1cf1-11eb-8d20-dde0138e0de1.png)

**Comment by wonder13662** [comment]
<img width="1440" alt="Screen Shot 2020-11-02 at 6 33 29 PM" src="https://user-images.githubusercontent.com/15767104/97852339-f377fb00-1d39-11eb-8163-c93d78a9c1fa.png">
버튼 삐져 나감
