### ISSUE TITLE
직원 - 칭찬하기 모달 개선

### ISSUE THREAD

**Issue by juhyun94** [wonder13662/barogo-passport#53]
![image](https://user-images.githubusercontent.com/73247309/97447625-1473d100-1973-11eb-8740-ccac400c2105.png)

- [x] "다음 달 까지 **OO**번" 에서 개수 텍스트 컬러 파란색으로 변경
- [x] B,A,R,O,GO 선택 시 각각의 의미 텍스트필드에 placeholder로 표현하기.
ex) Respect 선택 시 => '존중하는 마음'
- [x] 저장 버튼 눌렀을 때 로딩하는 표현을 아래 둘 중 하나가 되면 자연스러울것같음.
1) modal 상단부분에 progress linear
2) 저장 button을 Depressed 스타일로 바꾸고 버튼에 Progress Circular
- [x] 각 직원별로 팀 이름이 노출되는 형식으로 변경(운영자 멀티 직원선택 참고)
- [x] 자신에게 칭찬 쓸수 없음

**Comment by Godeng** [comment]
placeholder 내용입니다.
- B : "최고의 전문가 / 소신 있게 의견을 제시하여 프로젝트 진행에 크게 도움이 되었어요."
- A : "진정성 있는 가치 추구 / 작은 도움에도 감사를 표현해주는 동료에요."
- R : "열린 마인드와 행복 / 업무가 손에 익을 때 까지 차분히 알려주셨어요."
- O : "열린 기회와 아이디어 / 생각이 달랐는데, 잘 중재해주셨어요."
- Go : "행동하는 도전가 / 팀에 도움이 되는 일이라면 먼저 나서는 동료에요."
