### ISSUE TITLE
전반적으로 로딩이 느리다!

### ISSUE THREAD

**Issue by Godeng** [wonder13662/barogo-passport#67]
## trigger
- 10월 30일 데모 과정에서 발견된 이슈

## 개요
- 로그인 후, 내가 받은 칭찬 리스트 로딩
- 칭찬 완료 후, 칭찬 완료 결과 알림, 리스트 로딩
- 직원 목록 로딩

의 속도가 개선되었으면 좋겠다!

**Comment by wonder13662** [comment]
서울 리전 이전으로 속도 문제는 해결되어 이 이슈를 종료합니다.
