### ISSUE TITLE
칭찬하기 모달에서 '저장'을 여러번 누르면 칭찬이 중복 등록된다.

### ISSUE THREAD

**Issue by Godeng** [wonder13662/barogo-passport#79]
## 테스트 step
1. 유저가 칭찬하기 모달에 들어가서, 모든 항목을 입력한 후 칭찬 '저장'을 누른다.
2. 저장했다는 알림이 뜨거나 모달이 전환되기 전에 '저장'을 몇 번 더 누른다.

- expected result : 같은 내용의 칭찬이 한 번만 등록된다.
- actual result : 같은 내용의 칭찬이 여러 번 등록된다.

**Comment by wonder13662** [comment]
@Godeng 칭찬 작성 모달에서 저장을 누르면 바로 비활성 처리 및 로딩표시로 전환되어 위의 이슈는 발생하지 않습니다.
